"""empty message

Revision ID: 082830a74b85
Revises: c6c3baf2e143
Create Date: 2020-04-16 18:16:36.508528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '082830a74b85'
down_revision = 'c6c3baf2e143'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mention',
    sa.Column('user_fk', sa.BigInteger(), nullable=True),
    sa.Column('mentioned_fk', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['mentioned_fk'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_fk'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mention')
    # ### end Alembic commands ###
