"""empty message

Revision ID: 0bac8d13a0a4
Revises: 
Create Date: 2020-04-24 15:33:21.531300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bac8d13a0a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accesstokens',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('token', sa.String(length=50), nullable=True),
    sa.Column('credit', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('testers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('public_id', sa.BigInteger(), nullable=True),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('email', sa.VARCHAR(length=320), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.Column('token_fk', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['token_fk'], ['accesstokens.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('testers')
    op.drop_table('accesstokens')
    # ### end Alembic commands ###
