"""empty message

Revision ID: 0c3108c444b0
Revises: 0bac8d13a0a4
Create Date: 2020-04-24 15:52:30.992336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c3108c444b0'
down_revision = '0bac8d13a0a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'accesstokens', ['token'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'accesstokens', type_='unique')
    # ### end Alembic commands ###
