"""empty message

Revision ID: 12c90cead3e6
Revises: 89005a5f899d
Create Date: 2020-04-10 18:40:33.401172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12c90cead3e6'
down_revision = '89005a5f899d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweets', sa.Column('polarity', sa.Float(), nullable=True))
    op.add_column('tweets', sa.Column('subjectivity', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tweets', 'subjectivity')
    op.drop_column('tweets', 'polarity')
    # ### end Alembic commands ###
