"""empty message

Revision ID: 20e7fc5bc743
Revises: 082830a74b85
Create Date: 2020-04-16 18:57:53.869459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20e7fc5bc743'
down_revision = '082830a74b85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('tag', table_name='hashtags')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('tag', 'hashtags', ['tag'], unique=True)
    # ### end Alembic commands ###
