"""empty message

Revision ID: 34e6d21aa5a6
Revises: a0ce14616832
Create Date: 2020-04-20 01:58:11.163889

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '34e6d21aa5a6'
down_revision = 'a0ce14616832'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tweets', 'keyword')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweets', sa.Column('keyword', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))
    # ### end Alembic commands ###
