"""empty message

Revision ID: 6fc77e5a197e
Revises: b5c2141c9b32
Create Date: 2020-04-24 19:08:08.980366

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6fc77e5a197e'
down_revision = 'b5c2141c9b32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('testers', 'public_id',
               existing_type=mysql.BIGINT(display_width=20),
               type_=sa.String(length=36),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('testers', 'public_id',
               existing_type=sa.String(length=36),
               type_=mysql.BIGINT(display_width=20),
               existing_nullable=True)
    # ### end Alembic commands ###
