"""empty message

Revision ID: 7052a27716e3
Revises: 
Create Date: 2020-04-07 11:58:07.531691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7052a27716e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emojis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emoji', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hashtags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('screen_name', sa.String(length=50), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('followers', sa.Integer(), nullable=True),
    sa.Column('statuses', sa.Integer(), nullable=True),
    sa.Column('friends', sa.Integer(), nullable=True),
    sa.Column('inlists', sa.Integer(), nullable=True),
    sa.Column('seniority', sa.DateTime(), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mentions',
    sa.Column('mention_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('mentioned_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mentioned_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('mention_id')
    )
    op.create_table('tweets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=280), nullable=True),
    sa.Column('language', sa.String(length=4), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('retweets', sa.Integer(), nullable=True),
    sa.Column('favorites', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tweet_emoji',
    sa.Column('tweet_id', sa.Integer(), nullable=True),
    sa.Column('emoji_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['emoji_id'], ['emojis.id'], ),
    sa.ForeignKeyConstraint(['tweet_id'], ['tweets.id'], )
    )
    op.create_table('tweet_hashtag',
    sa.Column('tweet_id', sa.Integer(), nullable=True),
    sa.Column('hashtag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hashtag_id'], ['hashtags.id'], ),
    sa.ForeignKeyConstraint(['tweet_id'], ['tweets.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tweet_hashtag')
    op.drop_table('tweet_emoji')
    op.drop_table('tweets')
    op.drop_table('mentions')
    op.drop_table('users')
    op.drop_table('hashtags')
    op.drop_table('emojis')
    # ### end Alembic commands ###
