"""empty message

Revision ID: 89005a5f899d
Revises: 7052a27716e3
Create Date: 2020-04-09 17:36:34.062738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89005a5f899d'
down_revision = '7052a27716e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweets', sa.Column('keyword', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tweets', 'keyword')
    # ### end Alembic commands ###
