"""empty message

Revision ID: a0ce14616832
Revises: 
Create Date: 2020-04-20 01:26:13.671352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0ce14616832'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hashtags',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tag', sa.VARCHAR(length=280), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keywords',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('keyword', sa.VARCHAR(length=280), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('screen_name', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('seniority', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mention',
    sa.Column('user_fk', sa.BigInteger(), nullable=True),
    sa.Column('mentioned_fk', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['mentioned_fk'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_fk'], ['users.id'], )
    )
    op.create_table('tweets',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.String(length=280), nullable=True),
    sa.Column('language', sa.String(length=4), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('country', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('retweets', sa.Integer(), nullable=True),
    sa.Column('favorites', sa.Integer(), nullable=True),
    sa.Column('keyword', sa.Text(), nullable=True),
    sa.Column('polarity', sa.Float(), nullable=True),
    sa.Column('subjectivity', sa.Float(), nullable=True),
    sa.Column('user_fk', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user_fk'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tweet_hashtag',
    sa.Column('tweet_id', sa.BigInteger(), nullable=False),
    sa.Column('hashtag_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['hashtag_id'], ['hashtags.id'], ),
    sa.ForeignKeyConstraint(['tweet_id'], ['tweets.id'], ),
    sa.PrimaryKeyConstraint('tweet_id', 'hashtag_id')
    )
    op.create_table('tweet_keyword',
    sa.Column('tweet_id', sa.BigInteger(), nullable=False),
    sa.Column('keyword_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ),
    sa.ForeignKeyConstraint(['tweet_id'], ['tweets.id'], ),
    sa.PrimaryKeyConstraint('tweet_id', 'keyword_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tweet_keyword')
    op.drop_table('tweet_hashtag')
    op.drop_table('tweets')
    op.drop_table('mention')
    op.drop_table('users')
    op.drop_table('keywords')
    op.drop_table('hashtags')
    # ### end Alembic commands ###
