"""empty message

Revision ID: b5c2141c9b32
Revises: 0c3108c444b0
Create Date: 2020-04-24 16:24:51.929414

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b5c2141c9b32'
down_revision = '0c3108c444b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('testers', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('testers', sa.Column('username', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True))
    # ### end Alembic commands ###
