"""empty message

Revision ID: c6c3baf2e143
Revises: 60719e840889
Create Date: 2020-04-16 17:00:40.742536

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c6c3baf2e143'
down_revision = '60719e840889'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mentions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mentions',
    sa.Column('mention_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('mentioned_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['mentioned_id'], ['users.id'], name='mentions_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='mentions_ibfk_2'),
    sa.PrimaryKeyConstraint('mention_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
